# apps/backstage.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ethanellison/data-idp.git # Replace with your repo URL
    targetRevision: HEAD
    path: charts/backstage
    helm:
      valueFiles:
        - ../environments/dev/backstage-values.yaml # Environment-specific overrides
  destination:
    server: https://kubernetes.default.svc
    namespace: backstage # Target namespace for Backstage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
